export const items = [
  { id: 1, text: "fresh apples", slug: "fresh-apples" },
  { id: 2, text: "Ire's tomato soup", slug: "ires-tomato-soup" },
  { id: 3, text: "towering mountains", slug: "towering-mountains" },
  { id: 4, text: "old books", slug: "old-books" },
  { id: 5, text: "wooden chairs", slug: "wooden-chairs" },
  { id: 6, text: "sharp pencils", slug: "sharp-pencils" },
  { id: 7, text: "playful dogs", slug: "playful-dogs" },
  { id: 8, text: "sturdy bridges", slug: "sturdy-bridges" },
  { id: 9, text: "sweet cupcakes", slug: "sweet-cupcakes" },
  { id: 10, text: "acoustic guitars", slug: "acoustic-guitars" },
  { id: 11, text: "futuristic robots", slug: "futuristic-robots" },
  { id: 12, text: "Kae Tempest' lyrics", slug: "kae-tempest-lyrics" },
  {
    id: 13,
    text: "Paul B. Preciado's Can the monster speak?",
    slug: "paul-b-preciados-can-the-monster-speak",
  },
  { id: 14, text: "Ian Cheng games", slug: "ian-cheng-games" },
  {
    id: 15,
    text: "the hole in our living-room curtain",
    slug: "the-hole-in-our-living-room-curtain",
  },
  { id: 16, text: "the sound of a train", slug: "the-sound-of-a-train" },
  { id: 17, text: "the smell of rain", slug: "the-smell-of-rain" },
  { id: 18, text: "the taste of coffee", slug: "the-taste-of-coffee" },
  {
    id: 19,
    text: "the feel of a soft pillow",
    slug: "the-feel-of-a-soft-pillow",
  },
  { id: 20, text: "rustling leaves", slug: "rustling-leaves" },
  { id: 21, text: "morning dew", slug: "morning-dew" },
  { id: 22, text: "fresh mint tea", slug: "fresh-mint-tea" },
  { id: 23, text: "ancient ruins", slug: "ancient-ruins" },
  { id: 24, text: "chocolate truffles", slug: "chocolate-truffles" },
  { id: 25, text: "electric violins", slug: "electric-violins" },
  { id: 26, text: "vintage computers", slug: "vintage-computers" },
  { id: 27, text: "poetry notebooks", slug: "poetry-notebooks" },
  { id: 28, text: "philosophical essays", slug: "philosophical-essays" },
  { id: 29, text: "digital art", slug: "digital-art" },
  { id: 30, text: "city skylines", slug: "city-skylines" },
  { id: 31, text: "ocean waves", slug: "ocean-waves" },
  { id: 32, text: "autumn colors", slug: "autumn-colors" },
  { id: 33, text: "herbal gardens", slug: "herbal-gardens" },
  { id: 34, text: "warm blankets", slug: "warm-blankets" },
  { id: 35, text: "distant stars", slug: "distant-stars" },
  { id: 36, text: "morning fog", slug: "morning-fog" },
  { id: 37, text: "mountain streams", slug: "mountain-streams" },
  { id: 38, text: "desert sunsets", slug: "desert-sunsets" },
];
