export const items = [
  { id: 1, text: "fresh apples" },
  { id: 2, text: "Ire's tomato soup" },
  { id: 3, text: "towering mountains" },
  { id: 4, text: "old books" },
  { id: 5, text: "wooden chairs" },
  { id: 6, text: "sharp pencils" },
  { id: 7, text: "playful dogs" },
  { id: 8, text: "sturdy bridges" },
  { id: 9, text: "sweet cupcakes" },
  { id: 10, text: "acoustic guitars" },
  { id: 11, text: "futuristic robots" },
  { id: 12, text: "Kae Tempest' lyrics" },
  { id: 13, text: "Paul B. Preciado's Can the monster speak?" },
  { id: 14, text: "Ian Cheng games" },
  { id: 15, text: "the hole in our living-room curtain" },
  { id: 16, text: "the sound of a train" },
  { id: 17, text: "the smell of rain" },
  { id: 18, text: "the taste of coffee" },
  { id: 19, text: "the feel of a soft pillow" },
  { id: 20, text: "rustling leaves" },
  { id: 21, text: "morning dew" },
  { id: 22, text: "fresh mint tea" },
  { id: 23, text: "ancient ruins" },
  { id: 24, text: "chocolate truffles" },
  { id: 25, text: "electric violins" },
  { id: 26, text: "vintage computers" },
  { id: 27, text: "poetry notebooks" },
  { id: 28, text: "philosophical essays" },
  { id: 29, text: "digital art" },
  { id: 30, text: "city skylines" },
  { id: 31, text: "ocean waves" },
  { id: 32, text: "autumn colors" },
  { id: 33, text: "herbal gardens" },
  { id: 34, text: "warm blankets" },
  { id: 35, text: "distant stars" },
  { id: 36, text: "morning fog" },
  { id: 37, text: "mountain streams" },
  { id: 38, text: "desert sunsets" },
];
